apiVersion: v1
kind: Secret
metadata:
  name: app-passwords
  namespace: bakery
  labels:
    app.kubernetes.io/part-of: crumb-and-ember
    bakery.dev/managed-by: generate-app-secrets
  annotations:
    bakery.dev/algorithm: "sha256(password)"
    bakery.dev/format: "username:sha256_hash"
type: Opaque
stringData:
  passwords.txt: |
    amelie:7824e0764d79dd525f665d48e0038138cd069fce242b1d8a7b0f6b41f1a3d1be
    tomas:fbb1eeb89d064f2680346a80fc5c249bde3f73179ebd955b226aadf6d9abec7b
